[[ROOT]]
arch = "x86_64"
git-tree-sha1 = "883dde52995ca9517b0284d7d7f324e945daf399"
libc = "glibc"
os = "linux"

    [[ROOT.download]]
    sha256 = "a57bf62dc2a22d6a6cfbc701be05b647ee85fb19ac0a321feed56fea81699f3a"
    url = "https://github.com/grasph/ROOT_jll/releases/download/ROOT-v6.32.6+1/ROOT.v6.32.6.x86_64-linux-gnu.tar.gz"
