[[ROOT]]
arch = "x86_64"
git-tree-sha1 = "695eeb071941db39c7ba358689ce4c28e7b37f8b"
libc = "glibc"
os = "linux"

    [[ROOT.download]]
    sha256 = "df9b23f3beda664f620eed10304aeb9f9dbc6fbe91e176628bb63ecc9def8505"
    url = "https://github.com/grasph/ROOT_jll/releases/download/ROOT-v6.32.6+5/ROOT.v6.32.6.x86_64-linux-gnu.tar.gz"
