# Autogenerated wrapper script for ROOT_jll for x86_64-linux-gnu
export libCore, libGeom, libGraf, libGraf3d, libHist, libImt, libPhysics, libPostscript, libROOTVecOps, libRint, libTree, libTreePlayer, root

using Xorg_libX11_jll
using Xorg_libXpm_jll
using Xorg_libXft_jll
using oneTBB_jll
using VDT_jll
using XRootD_jll
using LAPACK_jll
using Lz4_jll
using FFTW_jll
using Giflib_jll
using Zstd_jll
using PCRE_jll
using Graphviz_jll
using xxHash_jll
using XZ_jll
using Librsvg_jll
using FreeType2_jll
using Xorg_libICE_jll
using Xorg_libSM_jll
using Xorg_libXfixes_jll
using Xorg_libXi_jll
using Xorg_libXinerama_jll
using Xorg_libXmu_jll
using Xorg_libXt_jll
using Xorg_libXtst_jll
using Xorg_xcb_util_jll
using Xorg_libxkbfile_jll
using Libglvnd_jll
using OpenBLAS_jll
using OpenSSL_jll
using GLEW_jll
using GLU_jll
using LibStdCxx_jll
using Fontconfig_jll
JLLWrappers.@generate_wrapper_header("ROOT")
JLLWrappers.@declare_library_product(libCore, "libCore.so")
JLLWrappers.@declare_library_product(libGeom, "libGeom.so")
JLLWrappers.@declare_library_product(libGraf, "libGraf.so")
JLLWrappers.@declare_library_product(libGraf3d, "libGraf3d.so")
JLLWrappers.@declare_library_product(libHist, "libHist.so")
JLLWrappers.@declare_library_product(libImt, "libImt.so")
JLLWrappers.@declare_library_product(libPhysics, "libPhysics.so")
JLLWrappers.@declare_library_product(libPostscript, "libPostscript.so")
JLLWrappers.@declare_library_product(libROOTVecOps, "libROOTVecOps.so")
JLLWrappers.@declare_library_product(libRint, "libRint.so")
JLLWrappers.@declare_library_product(libTree, "libTree.so")
JLLWrappers.@declare_library_product(libTreePlayer, "libTreePlayer.so")
JLLWrappers.@declare_executable_product(root)
function __init__()
    JLLWrappers.@generate_init_header(Xorg_libX11_jll, Xorg_libXpm_jll, Xorg_libXft_jll, oneTBB_jll, VDT_jll, XRootD_jll, LAPACK_jll, Lz4_jll, FFTW_jll, Giflib_jll, Zstd_jll, PCRE_jll, Graphviz_jll, xxHash_jll, XZ_jll, Librsvg_jll, FreeType2_jll, Xorg_libICE_jll, Xorg_libSM_jll, Xorg_libXfixes_jll, Xorg_libXi_jll, Xorg_libXinerama_jll, Xorg_libXmu_jll, Xorg_libXt_jll, Xorg_libXtst_jll, Xorg_xcb_util_jll, Xorg_libxkbfile_jll, Libglvnd_jll, OpenBLAS_jll, OpenSSL_jll, GLEW_jll, GLU_jll, LibStdCxx_jll, Fontconfig_jll)
    JLLWrappers.@init_library_product(
        libCore,
        "lib/libCore.so",
        nothing,
    )

    JLLWrappers.@init_library_product(
        libGeom,
        "lib/libGeom.so",
        nothing,
    )

    JLLWrappers.@init_library_product(
        libGraf,
        "lib/libGraf.so",
        nothing,
    )

    JLLWrappers.@init_library_product(
        libGraf3d,
        "lib/libGraf3d.so",
        nothing,
    )

    JLLWrappers.@init_library_product(
        libHist,
        "lib/libHist.so",
        nothing,
    )

    JLLWrappers.@init_library_product(
        libImt,
        "lib/libImt.so",
        nothing,
    )

    JLLWrappers.@init_library_product(
        libPhysics,
        "lib/libPhysics.so",
        nothing,
    )

    JLLWrappers.@init_library_product(
        libPostscript,
        "lib/libPostscript.so",
        nothing,
    )

    JLLWrappers.@init_library_product(
        libROOTVecOps,
        "lib/libROOTVecOps.so",
        nothing,
    )

    JLLWrappers.@init_library_product(
        libRint,
        "lib/libRint.so",
        nothing,
    )

    JLLWrappers.@init_library_product(
        libTree,
        "lib/libTree.so",
        nothing,
    )

    JLLWrappers.@init_library_product(
        libTreePlayer,
        "lib/libTreePlayer.so",
        nothing,
    )

    JLLWrappers.@init_executable_product(
        root,
        "bin/root",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
